# name: Deploy ROS application 🚀

# on:

#   push:
#     branches:
#       - main
#       - master

#   pull_request:
#     branches:
#       - main
#       - master

# jobs:

#   robotair:

#     name: Deploy ROS application
#     runs-on: ubuntu-latest

#     steps:

#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Export repository secrets as envfoxyment variables
#         uses: oNaiPs/secrets-to-env-action@v1.4
#         with:
#           secrets: ${{ toJSON(secrets) }}
      
#       - name: Install Rigel
#         run: sudo apt update && pip install git+https://github.com/rigel-ros/rigel@develop

#       - name: Show Docker file generated
#         run: |
#           rigel run job dockerfile 
#           cat Dockerfile

#       - name: Deploy ROS application using Rigel
#         run: rigel run sequence robotair